spring:
  application:
    name: carnet-de-sante

  datasource:
    url: jdbc:postgresql://localhost:5432/carnet_de_sante
    username: postgres
    password: Gunnersfan.33
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public

jwt:
  secret: Y2FybmV0X2RlX3NhbnRlX3NlY3JldF9rZXlfMjAyNl92ZXJ5X3NlY3VyZV9kb19ub3RfdXNlX2luX3Byb2R1Y3Rpb24=
  expiration: 86400000

logging:
  level:
    root: INFO
    com.example.carnet_de_sante: DEBUG
    liquibase: DEBUG